// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace StaffHabit.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class ModifiedHabitId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "staff_dev",
                table: "habits",
                keyColumn: "id",
                keyValue: "6c00a976-04e3-4ea9-963b-36806b9ca2a2");

            migrationBuilder.DeleteData(
                schema: "staff_dev",
                table: "habits",
                keyColumn: "id",
                keyValue: "bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630");

            migrationBuilder.InsertData(
                schema: "staff_dev",
                table: "habits",
                columns: new[] { "id", "frequency_times_period", "frequency_type", "created_at_utc", "description", "end_date", "is_archived", "last_completed_at_utc", "name", "status", "type", "updated_at_utc", "milestone_current", "milestone_target", "target_unit", "target_value" },
                values: new object[,]
                {
                    { "h_6c00a976-04e3-4ea9-963b-36806b9ca2a2", 1, 2, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "This is a test habit", null, false, null, "Test Habit", 1, 1, null, 0, 10, "times", 2 },
                    { "h_bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630", 1, 1, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "This is a test habit two", null, false, null, "Test Habit Two", 1, 1, null, 2, 4, "times", 3 }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "staff_dev",
                table: "habits",
                keyColumn: "id",
                keyValue: "h_6c00a976-04e3-4ea9-963b-36806b9ca2a2");

            migrationBuilder.DeleteData(
                schema: "staff_dev",
                table: "habits",
                keyColumn: "id",
                keyValue: "h_bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630");

            migrationBuilder.InsertData(
                schema: "staff_dev",
                table: "habits",
                columns: new[] { "id", "created_at_utc", "description", "end_date", "is_archived", "last_completed_at_utc", "name", "status", "type", "updated_at_utc", "frequency_times_period", "frequency_type", "milestone_current", "milestone_target", "target_unit", "target_value" },
                values: new object[,]
                {
                    { "6c00a976-04e3-4ea9-963b-36806b9ca2a2", new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "This is a test habit", null, false, null, "Test Habit", 1, 1, null, 1, 2, 0, 10, "times", 2 },
                    { "bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630", new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "This is a test habit two", null, false, null, "Test Habit Two", 1, 1, null, 1, 1, 2, 4, "times", 3 }
                });
        }
    }
}
