// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StaffHabit.Api.Database;

#nullable disable

namespace StaffHabit.Api.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250520001825_ModifiedCreatedProperty")]
    partial class ModifiedCreatedProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("staff_dev")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StaffHabit.Api.Entities.Habit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.ToTable("habits", "staff_dev");

                    b.HasData(
                        new
                        {
                            Id = "h_6c00a976-04e3-4ea9-963b-36806b9ca2a2",
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This is a test habit",
                            IsArchived = false,
                            Name = "Test Habit",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = "h_bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630",
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This is a test habit two",
                            IsArchived = false,
                            Name = "Test Habit Two",
                            Status = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("StaffHabit.Api.Entities.Habit", b =>
                {
                    b.OwnsOne("StaffHabit.Api.Entities.Frequency", "Frequency", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("character varying(500)")
                                .HasColumnName("id");

                            b1.Property<int>("TimesPeriod")
                                .HasColumnType("integer")
                                .HasColumnName("frequency_times_period");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("frequency_type");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "staff_dev");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fk_habits_habits_id");

                            b1.HasData(
                                new
                                {
                                    HabitId = "h_6c00a976-04e3-4ea9-963b-36806b9ca2a2",
                                    TimesPeriod = 1,
                                    Type = 2
                                },
                                new
                                {
                                    HabitId = "h_bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630",
                                    TimesPeriod = 1,
                                    Type = 1
                                });
                        });

                    b.OwnsOne("StaffHabit.Api.Entities.Milestone", "Milestone", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("character varying(500)")
                                .HasColumnName("id");

                            b1.Property<int>("Current")
                                .HasColumnType("integer")
                                .HasColumnName("milestone_current");

                            b1.Property<int>("Target")
                                .HasColumnType("integer")
                                .HasColumnName("milestone_target");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "staff_dev");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fk_habits_habits_id");

                            b1.HasData(
                                new
                                {
                                    HabitId = "h_6c00a976-04e3-4ea9-963b-36806b9ca2a2",
                                    Current = 0,
                                    Target = 10
                                },
                                new
                                {
                                    HabitId = "h_bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630",
                                    Current = 2,
                                    Target = 4
                                });
                        });

                    b.OwnsOne("StaffHabit.Api.Entities.Target", "Target", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("character varying(500)")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("target_unit");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("target_value");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "staff_dev");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fk_habits_habits_id");

                            b1.HasData(
                                new
                                {
                                    HabitId = "h_6c00a976-04e3-4ea9-963b-36806b9ca2a2",
                                    Unit = "times",
                                    Value = 2
                                },
                                new
                                {
                                    HabitId = "h_bc2ed4a9-c28c-4bd8-b60e-35d4b70ef630",
                                    Unit = "times",
                                    Value = 3
                                });
                        });

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
